default: &default
 adapter: postgresql
 encoding: utf8
 host: localhost
 username: postgres
 password: postgres
 pool: 5
 min_messages: WARNING

development:
 <<: *default
 database: basic_react_apiapp_development
